### ISSUE TITLE
game crashes if screen too wide

### ISSUE THREAD

**Issue by girst** [Capuno/Lander#12]
determined experimentally. 

game crashes if the terminal is wider than 191 columns. 

valgrind says, an invalid write was performed by createRock (where do you allocate memory for rocks[]? -- zero-sized arrays are undefined behaviour, aren't they?)

**Comment by Capuno** [comment]
rocks[] crashes it when it has an id higher than 190.

No idea why tho...

**Comment by girst** [comment]
I am a C guy, not a C++ one, but I guess, that the rocks[0] in line 24 is the culprit. according to the c++ standard, 0-length arrays are not allowed (couldn't determine if a gnu extension exists). 

putting a constant there fixes the problem. e.g. `24s/0/256`

i'm relatively sure you are writing beyond the memory reserved for global variables, but i'm too lazy to go deeper into that right now ;)

**Comment by Capuno** [comment]
Thanks again girst!

**Comment by girst** [comment]
always happy to help. you should probably limit the size of the playing field, because now the game crashes when i resize my terminal to be larger than 256 columns (which is quite easy when you use `xterm`/`urxvt` with the default 10px font and a fullhd monitor). 

or alternatively, set the array size to something comically huge, like 1280 (that won't crash, even when maximized on a 4k monitor, according to my back-of-a-napkin-calculations)

**Comment by MrWhiteGoat** [comment]
@girst I tried making the array 100 in size a while ago, but it still crashes...
