### ISSUE TITLE
Laser changing color to red

### ISSUE THREAD

**Issue by Capuno** [Capuno/Lander#8]
fix pls to solid blue

**Comment by MrWhiteGoat** [comment]
@Capuno  Not sure on how to do this atm, cuz if we prioritise the laser, the red enemies can turn blue...
Wait till weekends and we fix all these bugs?

**Comment by Capuno** [comment]
Ok this is not important tho, it also looks cool, i'll close it until we got less bugs to fix.

**Comment by MrWhiteGoat** [comment]
Sure, though I'm pretty sure that the laser doesn't turn red... Didn't see this problem when I played. Maybe because I don't play it that much.
